[project]
name = "hat-doit"
version = "0.15.9"
description = "Hat build utility functions"
readme = "README.rst"
requires-python = ">=3.10"
license = {text = "Apache-2.0"}
dependencies = [
    "doit >=0.36.0",
    "flake8 >=6.1.0",
    "furo >=2023.9.10",
    "mkwhl ~=0.3.1",
    "packaging >=23.1",
    "pdoc >=14.2.0",
    "pytest >=7.4.3",
    "pytest-asyncio >=0.21.1",
    "pytest-cov >=4.1.0",
    "pytest-timeout >=2.2.0",
    "sphinx >=7.2.6",
    "tomli ~=2.0.1",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License"
]

[project.urls]
Homepage = "http://hat-open.com"
Repository = "https://github.com/hat-open/hat-doit.git"

[build-system]
build-backend = "hat.doit.pep517"
backend-path = ["src_py"]
requires = [
    "doit",
    "packaging",
    "tomli"
]
