[project]
name = "hat-doit"
version = "0.15.2"
description = "Hat build utility functions"
readme = "README.rst"
requires-python = ">=3.10"
license = {text = "Apache-2.0"}
dependencies = [
    "doit >=0.36.0",
    "mkwhl ~=0.2.4",
    "packaging >=23.1",
    "tomli ~=2.0.1",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License"
]

[project.urls]
Homepage = "http://hat-open.com"
Repository = "https://github.com/hat-open/hat-doit.git"

[project.optional-dependencies]
flake8 = ["flake8 >=6.1.0"]
pdoc = ["pdoc >=14.0.0"]
pytest = [
    "pytest >=7.4.0",
    "pytest-asyncio >=0.21.1",
    "pytest-cov >=4.1.0",
    "pytest-timeout >=2.1.0",
]
sphinx = [
    "furo >=2023.7.26",
    "sphinx >=7.1.2",
]

[build-system]
build-backend = "hat.doit.pep517"
backend-path = ["src_py"]
requires = [
    "doit",
    "packaging",
    "tomli"
]
